apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: nexus.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-nexus-repository-manager
                port:
                  number: 8081
