apiVersion: v2
name: nginx-ingress-controller
description: A Helm chart for Nginx Ingress Controller
type: application
version: 0.1.0
appVersion: "4.9.0"

dependencies:
  - name: ingress-nginx
    version: "4.9.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
