apiVersion: v2
name: vault
description: A Helm chart for Vault secret management
type: application
version: 0.1.0
appVersion: "1.15.0"

dependencies:
  - name: vault
    version: "0.27.0"
    repository: "https://helm.releases.hashicorp.com"
