{{- if or .Values.secrets.mongodbUri .Values.secrets.extra }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nti-app.fullname" . }}-secrets
  labels:
    {{- include "nti-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.mongodbUri }}
  mongodb-uri: {{ .Values.secrets.mongodbUri | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extra }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
