apiVersion: v2
name: datadog
description: Datadog Agent for Kubernetes monitoring
type: application
version: 1.0.0
appVersion: "7"

dependencies:
  - name: datadog
    version: "3.x.x"
    repository: "https://helm.datadoghq.com"
